#####################################################################
#  GitHub Action to perform a rollback of the previous update by
#  executing the flowfiles/liquibase-rollback.flowfile.yaml from
#  the adeelmalik78/Automations repository.
#
#  This workflow uses a workflow_dispatch trigger, and only allows
#  for manual execution. To run the workflow:
#  1. Go to the "Actions" tab of the repository.
#  2. Select the Liquibase Pro Rollback Utility.
#  3. Select the "Run Workflow button".
#  4. In the popup enter the appropriate
#     values below and click the "Run Workflow":
#       -"Use workflow from" -> select the appropriate branch
#       -"Environment" -> enter the environment to rollback
#       -"Liquibase log level" -> INFO is chosen by default.
#                                 Increase the log level if needed.
#
#####################################################################
name: 'Liquibase Pro Rollback One Update Workflow'
run-name: Rollback one update from ${{ inputs.environment }} using branch ${{github.ref}} by ${{ github.actor }}

on:

  workflow_dispatch:
    inputs:
      # The type 'environment' will automatically pull in the environments created in Settings->Environments
      environment:
        description: 'Environment:'
        type: environment
        default: 'DEV'
        required: true
      # For more info on log level, see: https://docs.liquibase.com/parameters/log-level.html
      log-level:
        description: 'Liquibase log level'
        required: false
        default: 'INFO'
        type: choice
        options: ['SEVERE','WARNING','INFO','FINE','OFF']

####################################################################
#  Set up the environment
#####################################################################
env:

  LIQUIBASE_IO_API_URL: "https://demo.liquibase.xyz/api/"

jobs:
  ####################################################################
  #  Initialization
  ####################################################################
  init:
    name: Initialization
    runs-on: [ ubuntu-latest ]
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}

    steps:
      # Cancel any previous runs that are not completed for this workflow
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      # Determine the environment based on the branch(es) that triggered this workflow.
      # Output "DEV", "QA", or "PROD" to $GITHUB_OUTPUT where job output parameters are
      # shared between jobs.
      - name: Set Environment
        id: set-environment
        run: |
          echo "environment=DEV" >> $GITHUB_OUTPUT
          if [[ "${{ inputs.environment }}" == QA ]]; then
            echo "environment=QA" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ inputs.environment }}" == PROD ]]; then
            echo "environment=PROD" >> $GITHUB_OUTPUT
          fi

  ###################################################################
  #  Check out the source code
  ####################################################################
  checkout-repo:
    name: Check out repositories
    needs: [init]
    runs-on: [ubuntu-latest]

    steps:
      # Check out the database change configuration code and workflows
      - name: Checkout Database Change Configuration repo
        uses: actions/checkout@v3

      # Check out the SQL Repo to a folder, "liquibase-sql"
      - name: Checkout Database Change SQL repo
        uses: actions/checkout@v4
        with:
          repository: liquibase/cs-impl-guide-examples-sql
          path: liquibase-sql

  #########################################################################
  #  Roll back
  #########################################################################
  liquibase-rollback-action:
    name: Roll back one Liquibase update
    runs-on: [ubuntu-latest]
    needs: [checkout-repo, init]

    environment: ${{ inputs.environment }}

    steps:
      # Create a job from the workflow using the LBIO CLI:
      - name: Run rollback
        run: |
          echo 'Running workflow as job with curl API call (stubbed)...'
#          lbio workflow run {id} [--dispatch]
